### PR TITLE
seperated sam

### PR DESCRIPTION
**Pull request by trobinson1097**
what do you guys think?

### CODE REVIEW

**Review by CaseyFerebee — COMMENTED** [review]
well pepper jack is actually good so need to fix this

**Comment by SamThrasher96** [comment]
Hey!!

This deeply upsets me because my name is not Sammy and never will be. Please fix expeditiously

**Review by SamThrasher96 — CHANGES_REQUESTED** [review]
See previous comment

**Review by SamThrasher96 — APPROVED** [review]
heeheehaha

**Pull request merged**
